#define Showdown_Delay 100

void LED_Showdown() {
  digitalWrite(led_blue, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_green, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_yellow, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_red, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_blue, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_green, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_yellow, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_red, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_red, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_yellow, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_green, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_blue, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_blue, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_green, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_yellow, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_red, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_red, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_yellow, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_green, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_blue, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_red, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_yellow, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_green, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_blue, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_blue, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_green, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_yellow, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_red, HIGH);
  delay(Showdown_Delay);
  digitalWrite(led_red, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_yellow, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_green, LOW);
  delay(Showdown_Delay);
  digitalWrite(led_blue, LOW);
}
